spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5433/authservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

server:
  address: accounts.lostedin.com
  port: 8080

lostedin:
  config:
    token:
      access-token-expire-time-minutes: 30
      refresh-token-expire-time-days: 3
    response-code:
      code-expire-time-minutes: 5