spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5433/authservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

server:
  address: accounts.lostedin.com
  port: 8080

lostedin:
  config:
    token:
      # Time in minutes before access tokens expire (default: 30, min: 5, max: 60)
      access-token-expire-time-minutes: 30
      # Time in days before refresh tokens expire (default: 3, min: 1, max: 7)
      refresh-token-expire-time-days: 3
    response-code:
      # Time in minutes before response codes expire (default: 5, min: 1, max: 10)
      code-expire-time-minutes: 5