spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5433/authservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Можно поставить "validate", "update", "create", "create-drop"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true   # Логировать SQL-запросы (true/false)
    format-sql: true # Форматировать SQL-логи (если show-sql включен)